# Translations template for nova.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: nova\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-06-30 06:08+0000\n"
"PO-Revision-Date: 2014-06-14 19:30+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Portuguese (Brazil) (http://www.transifex.com/projects/p/nova/"
"language/pt_BR/)\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: nova/hooks.py:84
#, python-format
msgid "Fatal Exception running %(name)s pre-hook: %(obj)s"
msgstr ""

#: nova/hooks.py:89
#, python-format
msgid "Exception running %(name)s pre-hook: %(obj)s"
msgstr ""

#: nova/hooks.py:105
#, python-format
msgid "Fatal Exception running %(name)s post-hook: %(obj)s"
msgstr ""

#: nova/hooks.py:110
#, python-format
msgid "Exception running %(name)s post-hook: %(obj)s"
msgstr ""

#: nova/api/ec2/__init__.py:243
#, python-format
msgid "Keystone failure: %s"
msgstr ""

#: nova/objects/instance_fault.py:87
msgid "Failed to notify cells of instance fault"
msgstr "Falha ao notificar células de falha da instância"

#: nova/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Exceção original sendo descartada: %s"

#: nova/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "Exceção não esperada ocorreu %d vez(es)... tentando novamente."

#: nova/openstack/common/lockutils.py:120
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: nova/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr "em uma chamada de laço de duração fixa"

#: nova/openstack/common/loopingcall.py:136
msgid "in dynamic looping call"
msgstr "em chamada de laço dinâmico"

#: nova/openstack/common/periodic_task.py:179
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr "Erro durante %(full_task_name)s: %(e)s"

#: nova/openstack/common/policy.py:511
#, python-format
msgid "Failed to understand rule %s"
msgstr "Falha ao interpretar regra %s"

#: nova/openstack/common/policy.py:521
#, python-format
msgid "No handler for matches of kind %s"
msgstr "Nenhum manipulador para correspondências do tipo %s"

#: nova/openstack/common/policy.py:791
#, python-format
msgid "Failed to understand rule %r"
msgstr "Falha ao interpretar regra %r"

#: nova/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Exceção durante limpeza de RPC."

#: nova/openstack/common/service.py:276
msgid "Unhandled exception"
msgstr "Exceção não tratada"

#: nova/openstack/common/db/api.py:72
msgid "DB exceeded retry limit."
msgstr ""

#: nova/openstack/common/db/api.py:76
msgid "DB connection error."
msgstr ""

#: nova/openstack/common/db/sqlalchemy/session.py:460
msgid "DB exception wrapped."
msgstr "Exceção de BD incluída."

#: nova/openstack/common/db/sqlalchemy/test_migrations.py:267
#, python-format
msgid "Failed to migrate to version %s on engine %s"
msgstr ""

#: nova/virt/libvirt/driver.py:625
#, python-format
msgid "Nova requires libvirt version %(major)i.%(minor)i.%(micro)i or greater."
msgstr ""

#: nova/virt/libvirt/driver.py:749
#, python-format
msgid "Connection to libvirt failed: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:873
#, python-format
msgid "Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:889
msgid "During wait destroy, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:951
#, python-format
msgid "Error from libvirt during undefine. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:977
#, python-format
msgid "Error from libvirt during unfilter. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1389
msgid "attaching network adapter failed."
msgstr ""

#: nova/virt/libvirt/driver.py:1414
msgid "detaching network adapter failed."
msgstr ""

#: nova/virt/libvirt/driver.py:1663
msgid "Failed to send updated snapshot status to volume service."
msgstr ""

#: nova/virt/libvirt/driver.py:1749
msgid ""
"Unable to create quiesced VM snapshot, attempting again with quiescing "
"disabled."
msgstr ""

#: nova/virt/libvirt/driver.py:1755
msgid "Unable to create VM snapshot, failing volume_snapshot operation."
msgstr ""

#: nova/virt/libvirt/driver.py:1804
msgid ""
"Error occurred during volume_snapshot_create, sending error status to Cinder."
msgstr ""

#: nova/virt/libvirt/driver.py:1951
msgid ""
"Error occurred during volume_snapshot_delete, sending error status to Cinder."
msgstr ""

#: nova/virt/libvirt/driver.py:2416 nova/virt/libvirt/driver.py:2421
#, python-format
msgid "Error on '%(path)s' while checking direct I/O: '%(ex)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:2542
#, python-format
msgid "Error injecting data into image %(img_id)s (%(e)s)"
msgstr ""

#: nova/virt/libvirt/driver.py:2693
#, python-format
msgid "Creating config drive failed with error: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:2786
#, python-format
msgid "Attaching PCI devices %(dev)s to %(dom)s failed."
msgstr ""

#: nova/virt/libvirt/driver.py:3553
#, python-format
msgid "An error occurred while trying to define a domain with xml: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:3562
#, python-format
msgid "An error occurred while trying to launch a defined domain with xml: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:3571
#, python-format
msgid "An error occurred while enabling hairpin mode on domain with xml: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:3589
#, python-format
msgid "Neutron Reported failure on event %(event)s for instance %(uuid)s"
msgstr ""

#: nova/virt/libvirt/driver.py:3904
#, python-format
msgid ""
"Hostname has changed from %(old)s to %(new)s. A restart is required to take "
"effect."
msgstr ""

#: nova/virt/libvirt/driver.py:4481
#, python-format
msgid "Live Migration failure: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:5231
#, python-format
msgid "Failed to cleanup directory %(target)s: %(e)s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:202
#, python-format
msgid "Unable to preallocate_images=%(imgs)s at path: %(path)s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:230
#, python-format
msgid ""
"%(base)s virtual size %(base_size)s larger than flavor root disk size "
"%(size)s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:501
#, python-format
msgid "error opening rbd image %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:130
#, python-format
msgid "Error reading image info file %(filename)s: %(error)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:391
#, python-format
msgid "image %(id)s at (%(base_file)s): image verification failed"
msgstr ""

#: nova/virt/libvirt/imagecache.py:448
#, python-format
msgid "Failed to remove %(base_file)s, error was %(error)s"
msgstr ""

#: nova/virt/libvirt/lvm.py:201
#, python-format
msgid "ignoring unrecognized volume_clear='%s' value"
msgstr ""

#: nova/virt/libvirt/vif.py:548 nova/virt/libvirt/vif.py:572
#: nova/virt/libvirt/vif.py:596
msgid "Failed while plugging vif"
msgstr ""

#: nova/virt/libvirt/vif.py:644 nova/virt/libvirt/vif.py:676
#: nova/virt/libvirt/vif.py:695 nova/virt/libvirt/vif.py:717
#: nova/virt/libvirt/vif.py:737 nova/virt/libvirt/vif.py:762
#: nova/virt/libvirt/vif.py:784
msgid "Failed while unplugging vif"
msgstr ""

#: nova/virt/libvirt/volume.py:141
#, python-format
msgid "Unknown content in connection_info/access_mode: %s"
msgstr ""

#: nova/virt/libvirt/volume.py:666
#, python-format
msgid "Couldn't unmount the NFS share %s"
msgstr ""

#: nova/virt/libvirt/volume.py:815
#, python-format
msgid "Couldn't unmount the GlusterFS share %s"
msgstr ""
