# Translations template for nova.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 2014.2.dev374.g4e35f5f\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-06-30 06:08+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: nova/compute/manager.py:1998
msgid "No more network or fixed IP to be allocated"
msgstr ""

#: nova/consoleauth/manager.py:84
#, python-format
msgid "Token: %(token)s failed to save into memcached."
msgstr ""

#: nova/consoleauth/manager.py:95
#, python-format
msgid "Instance: %(instance_uuid)s failed to save into memcached"
msgstr ""

#: nova/openstack/common/loopingcall.py:82
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: nova/openstack/common/network_utils.py:146
msgid "tcp_keepidle not available on your system"
msgstr ""

#: nova/openstack/common/network_utils.py:153
msgid "tcp_keepintvl not available on your system"
msgstr ""

#: nova/openstack/common/network_utils.py:160
msgid "tcp_keepknt not available on your system"
msgstr ""

#: nova/openstack/common/service.py:363
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: nova/openstack/common/db/sqlalchemy/session.py:506
#, python-format
msgid "Database server has gone away: %s"
msgstr ""

#: nova/openstack/common/db/sqlalchemy/session.py:559
msgid "Unable to detect effective SQL mode"
msgstr ""

#: nova/openstack/common/db/sqlalchemy/session.py:567
#, python-format
msgid "MySQL SQL mode is '%s', consider enabling TRADITIONAL or STRICT_ALL_TABLES"
msgstr ""

#: nova/openstack/common/db/sqlalchemy/session.py:673
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: nova/openstack/common/db/sqlalchemy/utils.py:97
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: nova/scheduler/filters/core_filter.py:51
msgid "VCPUs not set; assuming CPU collection broken"
msgstr ""

#: nova/scheduler/filters/core_filter.py:92
#, python-format
msgid "Could not decode cpu_allocation_ratio: '%s'"
msgstr ""

#: nova/scheduler/filters/ram_filter.py:95
#, python-format
msgid "Could not decode ram_allocation_ratio: '%s'"
msgstr ""

#: nova/virt/libvirt/driver.py:368
#, python-format
msgid "Invalid cachemode %(cache_mode)s specified for disk type %(disk_type)s."
msgstr ""

#: nova/virt/libvirt/driver.py:606
#, python-format
msgid ""
"The libvirt driver is not tested on %(type)s/%(arch)s by the OpenStack "
"project and thus its quality can not be ensured. For more information, "
"see: https://wiki.openstack.org/wiki/HypervisorSupportMatrix"
msgstr ""

#: nova/virt/libvirt/driver.py:656
#, python-format
msgid "URI %(uri)s does not support events: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:672
#, python-format
msgid "URI %(uri)s does not support connection events: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:865
msgid "Cannot destroy instance, operation time out"
msgstr ""

#: nova/virt/libvirt/driver.py:971
msgid "Instance may be still running, destroy it again."
msgstr ""

#: nova/virt/libvirt/driver.py:1026
#, python-format
msgid "Ignoring Volume Error on vol %(vol_id)s during delete %(exc)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1076
#, python-format
msgid "Volume %(disk)s possibly unsafe to remove, please clean up manually"
msgstr ""

#: nova/virt/libvirt/driver.py:1357 nova/virt/libvirt/driver.py:1365
msgid "During detach_volume, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:1410
msgid "During detach_interface, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:1976
msgid "Failed to soft reboot instance. Trying hard reboot."
msgstr ""

#: nova/virt/libvirt/driver.py:2537
#, python-format
msgid "Image %s not found on disk storage. Continue without injecting data"
msgstr ""

#: nova/virt/libvirt/driver.py:2700
msgid "File injection into a boot from volume instance is not supported"
msgstr ""

#: nova/virt/libvirt/driver.py:2775
msgid "Instance disappeared while detaching a PCI device from it."
msgstr ""

#: nova/virt/libvirt/driver.py:2830
#, python-format
msgid "Cannot update service status on host: %s,since it is not registered."
msgstr ""

#: nova/virt/libvirt/driver.py:2833
#, python-format
msgid "Cannot update service status on host: %s,due to an unexpected exception."
msgstr ""

#: nova/virt/libvirt/driver.py:2861
#, python-format
msgid "URI %(uri)s does not support full set of host capabilities: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:3672
#, python-format
msgid "Timeout waiting for vif plugging callback for instance %(uuid)s"
msgstr ""

#: nova/virt/libvirt/driver.py:3750
msgid ""
"Cannot get the number of cpu, because this function is not implemented "
"for this platform. "
msgstr ""

#: nova/virt/libvirt/driver.py:3813
#, python-format
msgid "couldn't obtain the vpu count from domain id: %(id)s, exception: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4050
#, python-format
msgid "URI %(uri)s does not support listDevices: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4594
#, python-format
msgid "plug_vifs() failed %(cnt)d. Retry up to %(max_retry)d."
msgstr ""

#: nova/virt/libvirt/driver.py:4727
#, python-format
msgid ""
"Error from libvirt while getting description of %(instance_name)s: [Error"
" Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4805
#, python-format
msgid ""
"Periodic task is updating the host stat, it is trying to get disk "
"%(i_name)s, but disk file was removed by concurrent operations such as "
"resize."
msgstr ""

#: nova/virt/libvirt/driver.py:4811
#, python-format
msgid ""
"Periodic task is updating the host stat, it is trying to get disk "
"%(i_name)s, but access is denied. It is most likely due to a VM that "
"exists on the compute node but is not managed by Nova."
msgstr ""

#: nova/virt/libvirt/firewall.py:49
msgid ""
"Libvirt module could not be loaded. NWFilterFirewall will not work "
"correctly."
msgstr ""

#: nova/virt/libvirt/imagecache.py:318
#, python-format
msgid ""
"Instance %(instance)s is using a backing file %(backing)s which does not "
"appear in the image service"
msgstr ""

#: nova/virt/libvirt/imagecache.py:495
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): warning -- an absent base file is in "
"use! instances: %(instance_list)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:545
#, python-format
msgid "Unknown base file: %s"
msgstr ""

#: nova/virt/libvirt/lvm.py:68
#, python-format
msgid ""
"Volume group %(vg)s will not be able to hold sparse volume %(lv)s. "
"Virtual volume size is %(size)db, but free space on volume group is only "
"%(free_space)db."
msgstr ""

#: nova/virt/libvirt/utils.py:69 nova/virt/libvirt/utils.py:75
msgid "systool is not installed"
msgstr ""

#: nova/virt/libvirt/utils.py:242
#, python-format
msgid "rbd remove %(name)s in pool %(pool)s failed"
msgstr ""

#: nova/virt/libvirt/vif.py:827
#, python-format
msgid ""
"VIF driver \"%s\" is marked as deprecated and will be removed in the Juno"
" release."
msgstr ""

#: nova/virt/libvirt/volume.py:132
#, python-format
msgid "Unknown content in connection_info/qos_specs: %s"
msgstr ""

#: nova/virt/libvirt/volume.py:294
#, python-format
msgid ""
"ISCSI volume not yet found at: %(disk_dev)s. Will rescan & retry.  Try "
"number: %(tries)s"
msgstr ""

#: nova/virt/libvirt/volume.py:361
#, python-format
msgid "Unable to delete volume device %s"
msgstr ""

#: nova/virt/libvirt/volume.py:372
#, python-format
msgid ""
"Failed to remove multipath device descriptor %(dev_mapper)s. Exception "
"message: %(msg)s"
msgstr ""

#: nova/virt/libvirt/volume.py:694 nova/virt/libvirt/volume.py:843
#, python-format
msgid "%s is already mounted"
msgstr ""

#: nova/virt/libvirt/volume.py:739
#, python-format
msgid "AoE volume not yet found at: %(aoedevpath)s. Try number: %(tries)s"
msgstr ""

#: nova/virt/libvirt/volume.py:931
#, python-format
msgid ""
"Fibre volume not yet found at: %(mount_device)s. Will rescan & retry.  "
"Try number: %(tries)s"
msgstr ""

#: nova/virt/libvirt/volume.py:1033
msgid "Value required for 'scality_sofs_config'"
msgstr ""

#: nova/virt/libvirt/volume.py:1044
#, python-format
msgid "Cannot access 'scality_sofs_config': %s"
msgstr ""

#: nova/virt/libvirt/volume.py:1050
msgid "Cannot execute /sbin/mount.sofs"
msgstr ""

#: nova/virt/libvirt/volume.py:1065
msgid "Cannot mount Scality SOFS, check syslog for errors"
msgstr ""

